version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: .
    command: bash -c "python marketapi/manage.py migrate --noinput &&
              python marketapi/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/backend/marketapi/
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
