# Generated by Django 4.0.3 on 2022-05-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_product_order_products_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_received',
        ),
    ]
