# Generated by Django 4.0.3 on 2022-05-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_order_data_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='data',
            new_name='date',
        ),
    ]
