# Generated by Django 4.0.3 on 2022-05-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_order_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivery',
        ),
    ]
