# Generated by Django 4.0.3 on 2022-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_productimage_alter_orderstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображение товара'},
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(null=True, related_name='products', to='market.productimage', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
