# Generated by Django 4.0.3 on 2022-05-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_product_images_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
