# Generated by Django 4.0.3 on 2022-05-21 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_productimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product', verbose_name='Товар'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together={('order', 'title')},
        ),
    ]
